### ISSUE TITLE
PHP Warning: array_flip(): Can only flip STRING and INTEGER values

### ISSUE THREAD

**Issue by franzholz** [FriendsOfTYPO3/blog_example#10]
This happens in TYPO3 9.5 and PHP 7.3.

blog_example 9.5.0

>  Oops, an error occurred! Code: 202105041047528ec47c25 PHP Warning: array_flip(): Can only flip STRING and INTEGER values! in /var/www/html/typo3_src-9.5.24/typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php line 254 exception code:1476107295 file:/typo3/sysext/core/Classes/Error/ErrorHandler.php line:132 fh_debug trace: file: " line: function:handleError file: /typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php" line:254 function:array_flip file: /typo3/sysext/extbase/Classes/Mvc/Controller/ActionController.php" line:154 function:initializeActionMethodValidators file: /typo3/sysext/extbase/Classes/Mvc/Dispatcher.php" line:73 function:processRequest file: /typo3/sysext/extbase/Classes/Mvc/Web/FrontendRequestHandler.php" line:92 function:dispatch file: /typo3/sysext/extbase/Classes/Core/Bootstrap.php" line:172 function:handleRequest file: /typo3/sysext/extbase/Classes/Core/Bootstrap.php" line:159 function:handleRequest file: " line: function:run file: /typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php" line:5969 function:call_user_func_array file: /typo3/sysext/frontend/Classes/ContentObject/UserContentObject.php" line:41 function:callUserFunction file: /typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php" line:815 function:render file: /typo3/sysext/frontend/Classes/ContentObject/ContentObjectRenderer.php" line:731 function:render file: /typo3/sysext/fluid/Classes/ViewHelpers/CObjectViewHelper.php" line:189 function:cObjGetSingle

**Comment by franzholz** [comment]
I think this is a bug in TYPO3 9.5.

https://forge.typo3.org/issues/94055

**Comment by alexanderschnitzler** [comment]
This is not a core bug but wrong usage of the new annotation.

Please see this as a reference: https://docs.typo3.org/c/typo3/cms-core/master/en-us/Changelog/9.0/Feature-83094-ReplaceIgnorevalidationWithTYPO3CMSExtbaseAnnotationIgnoreValidation.html#

Wrong usage: `@TYPO3\CMS\Extbase\Annotation\IgnoreValidation $param`
Right usage: `@TYPO3\CMS\Extbase\Annotation\IgnoreValidation("param")`

**Comment by franzholz** [comment]
Fixed in 

https://github.com/FriendsOfTYPO3/blog_example/pull/11
