### ISSUE TITLE
question about ext_typoscript_setup.typoscript

### ISSUE THREAD

**Issue by franzholz** [FriendsOfTYPO3/blog_example#13]
Why is the file ext_typoscript_setup.typoscript needed?

see https://docs.typo3.org/m/typo3/reference-coreapi/master/en-us/ExtensionArchitecture/FilesAndLocations/Index.html .

All the persistence setup could be as well integrated into the static template 
 blog_example.git/blog_example/Configuration/TypoScript/setup.typoscript
.

**Comment by susannemoog** [comment]
It's meant as an example for the global, always loaded non-PID, non-site dependent configuration. It's not necessary to do it this way, however, it's a showcase for this kind of configuration. This might make sense if you are for example adding a backend module in an installation that does not have pages or a frontend and is only used for the backend functionality.

**Comment by franzholz** [comment]
If an extension only has a backend module, then it does not need any TypoScript. TypoScript is only available in the frontend, not in the backend.

**Comment by susannemoog** [comment]
Isn't it still the case that extbase loads mapping information from typoscript whether you use it in the frontend or not? maybe that changed in the meantime, but I thought that was still the case.

**Comment by franzholz** [comment]
I cannot imagine a situation where TypoScript is used in the backend. It is not used in the backend, because TSConfig is for the backend configuration. And the backend has no page id. 

However I have found this:

https://www.in2code.de/en/recent/php-typoscript-usage-in-backend-or-comand-context/


    use TYPO3\CMS\Core\TypoScript\TemplateService;
    use TYPO3\CMS\Core\Utility\GeneralUtility;

    $templateService = GeneralUtility::makeInstance(TemplateService::class);
   
   
typo3_src-10.4.10/typo3/sysext/extbase/Classes/Configuration/BackendConfigurationManager.php has this:

    /**
     * Returns TypoScript Setup array from current Environment.
     *
     * @return array the raw TypoScript setup
     */
    public function getTypoScriptSetup(): array
    {
        $pageId = $this->getCurrentPageId();

        if (!array_key_exists($pageId, $this->typoScriptSetupCache)) {
            /** @var TemplateService $template */
            $template = GeneralUtility::makeInstance(TemplateService::class);


So it seems your are right.

**Comment by linawolf** [comment]
You are right, TypoScript is still loaded in the backend in some use cases. The new module API coming with TYPO3 v12 will improve the situation.
