### ISSUE TITLE
f:form.textbox doesn't exist

### ISSUE THREAD

**Issue by MaikBeckmann** [FriendsOfTYPO3/blog_example#16]
Trying to create a new blog in the backend results in the following error:

`1/2) #1407060572 TYPO3Fluid\Fluid\Core\Parser\Exception
Fluid parse error in template Blog_action_new_2283f236712d836692c6313de3b58696003da241, line 24 at character 10. Error: The ViewHelper "<f:form.textbox>" could not be resolved.`

Pictures:
![Create new blog](https://user-images.githubusercontent.com/229995/142046567-a136d384-cd33-4219-9f39-542843ef2895.png)
![Error](https://user-images.githubusercontent.com/229995/142046702-1b46e9dc-1081-4f1b-a626-5116d85585e0.png)

Steps to reproduce
 - $ composer create-project typo3/cms-base-distribution:^11 blog-example
 - add repository "./packages/*" to composer.json 
 - clone this github repo into packages/blog_example
 - $ composer require friendsoftypo3/blog-example:@dev
 - create public/FIRST_INSTALL and setup installation
 - create root Page
 - Visit backend, go to Blog module and click the "+" button

Versions
 - PHP: 7.4.25
 - TYPO3: 11.5.3
 - blog_example: master

**Comment by linawolf** [comment]
solved
